package util;

/**
 * Created by LogiX on 2015-12-11.
 */
public enum Event {
    WRONG_PASSWORD,
    WRONG_USERNAME,
    PASSWORDS_DO_NOT_MATCH,
    USERNAME_ALREADY_IN_USE,
    USER_CREATE_SUCCESS,
    USER_UPDATE_SUCCESS,
    USER_UPDATE_FAILED,
    USER_DELETE_SUCCESS,
    USER_DELETE_FAILED,
    USER_SOCIALID_ALREADY_EXISTS,
    NO_SUCH_ATTENDANCE_TYPE_FOUND,
    REGISTER_ATTENDANCE_SUCCESS,
    REGISTER_ATTENDANCE_FAILED,
    DELETED_ATTENDANCE_SUCCESS,
    UPDATE_ATTENDANCE_SUCCESS,
    UPDATE_ATTENDANCE_FAILED,
    DELETED_ATTENDANCE_FAILED,
    NO_SUCH_USER_LEVEL_FOUND,
    USER_INVITE_SUCCESS,
    USER_INVITE_FAILED,
    CLASS_CREATE_SUCCESS,
    CLASS_CREATE_FAILED,
    CLASS_DELETE_SUCCESS,
    CLASS_DELETE_FAILED,
    PASSWORD_RESET_CREATE_SUCCESS,
    PASSWORD_RESET_CREATE_FAILED,
    PASSWORD_RESET_DELETE_SUCCESS,
    PASSWORD_RESET_DELETE_FAILED
}
